// NOTE: the config Stitch exported for this page had a syntax error (a missing closing brace),
// so the original HTML rendered with Tailwind's default theme. `intended` below is the repaired
// RCFI theme, matching the other academy pages.
const intended = {darkMode:"class",theme:{extend:{colors:{"surface-container-highest":"#d5e3fc","on-error":"#ffffff","tertiary-fixed":"#d1e8dd","primary-container":"#0b4a34","tertiary-fixed-dim":"#b5ccc2","surface-container":"#e6eeff","secondary-container":"#6cf8bb","surface-container-high":"#dce9ff","secondary-fixed-dim":"#4edea3","surface-container-low":"#eff4ff","on-tertiary-fixed":"#0b1f19","error":"#ba1a1a","on-primary-fixed-variant":"#14503a","primary-fixed":"#b4f0d1","surface-bright":"#f8f9ff","surface-tint":"#306951","on-secondary":"#ffffff","outline":"#707973","tertiary-container":"#31453e","surface-container-lowest":"#ffffff","primary":"#003221","inverse-primary":"#98d3b5","on-primary-container":"#7fb99c","on-tertiary":"#ffffff","on-primary-fixed":"#002114","inverse-surface":"#233144","on-primary":"#ffffff","on-surface-variant":"#404943","on-tertiary-container":"#9cb2a8","on-surface":"#0d1c2e","secondary-fixed":"#6ffbbe","inverse-on-surface":"#eaf1ff","on-error-container":"#93000a","on-secondary-fixed-variant":"#005236","surface":"#f8f9ff","surface-variant":"#d5e3fc","background":"#f8f9ff","error-container":"#ffdad6","on-background":"#0d1c2e","tertiary":"#1b2f28","primary-fixed-dim":"#98d3b5","surface-dim":"#ccdbf3","on-secondary-container":"#00714d","on-tertiary-fixed-variant":"#374b43","on-secondary-fixed":"#002113","secondary":"#006c49","outline-variant":"#c0c9c2"},borderRadius:{"DEFAULT":"0.25rem","lg":"0.5rem","xl":"0.75rem","full":"9999px"},spacing:{"space-xl":"2.5rem","margin":"2rem","space-md":"1rem","margin-mobile":"1rem","gutter-mobile":"1rem","space-lg":"1.5rem","space-sm":"0.5rem","gutter":"1.5rem","space-xs":"0.25rem"},fontFamily:{"display-lg":["Plus Jakarta Sans"],"body-lg":["Plus Jakarta Sans"],"headline-sm":["Plus Jakarta Sans"],"headline-md":["Plus Jakarta Sans"],"headline-lg-mobile":["Plus Jakarta Sans"],"label-sm":["Plus Jakarta Sans"],"title-md":["Plus Jakarta Sans"],"display-lg-mobile":["Plus Jakarta Sans"],"body-md":["Plus Jakarta Sans"],"headline-lg":["Plus Jakarta Sans"],"label-md":["Plus Jakarta Sans"]},fontSize:{"display-lg":["48px",{"lineHeight":"56px","letterSpacing":"-0.02em","fontWeight":"700"}],"body-lg":["16px",{"lineHeight":"26px","fontWeight":"400"}],"headline-sm":["20px",{"lineHeight":"28px","fontWeight":"600"}],"headline-md":["28px",{"lineHeight":"36px","letterSpacing":"-0.01em","fontWeight":"600"}],"headline-lg-mobile":["26px",{"lineHeight":"34px","letterSpacing":"-0.01em","fontWeight":"700"}],"label-sm":["11px",{"lineHeight":"16px","letterSpacing":"0.03em","fontWeight":"600"}],"title-md":["18px",{"lineHeight":"26px","fontWeight":"600"}],"display-lg-mobile":["32px",{"lineHeight":"40px","letterSpacing":"-0.01em","fontWeight":"700"}],"body-md":["14px",{"lineHeight":"22px","fontWeight":"400"}],"headline-lg":["36px",{"lineHeight":"44px","letterSpacing":"-0.02em","fontWeight":"700"}],"label-md":["13px",{"lineHeight":"18px","letterSpacing":"0.01em","fontWeight":"500"}]}}}};

const stitch = intended;

module.exports = {
  ...stitch,
  content: { relative: true, files: ["../../../app/academy/digital-trust-cyber/page.tsx"] },
  plugins: [],
};
