// Every page in the site (used by the /variants index).

export type SiteRoute = { path: string; title: string };

export const routes: SiteRoute[] = [
  { path: "/", title: "RCFI Technology — Building the Trust Layer for Africa's Digital Economy" },
  { path: "/about/", title: "About | RCFI Technology" },
  { path: "/careers/", title: "Careers & Attachment | RCFI Technology" },
  { path: "/contact/", title: "Contact | RCFI Technology" },
  { path: "/services/", title: "Services | RCFI Technology" },
  { path: "/services/digital-trust-pki/", title: "Digital Trust & PKI | RCFI Technology" },
  { path: "/services/cybersecurity-assurance/", title: "Cybersecurity & Assurance | RCFI Technology" },
  { path: "/services/data-analytics-ai/", title: "Data, Analytics & AI | RCFI Technology" },
  { path: "/services/digital-cloud-engineering/", title: "Digital & Cloud Engineering | RCFI Technology" },
  { path: "/services/digital-health-governance/", title: "Digital Health Governance | RCFI Technology" },
  { path: "/health-security/", title: "Health Security | RCFI Technology" },
  { path: "/products/certysign/", title: "CertySign — Digital Signatures, Certificates & Verification | RCFI" },
  { path: "/products/elano/", title: "Elano — Governance & Intelligence | RCFI" },
  { path: "/products/prezio/", title: "Prezio — Workflow & Approval Automation | RCFI" },
  { path: "/academy/", title: "RCFI Academy" },
  { path: "/academy/applied-data-ai/", title: "Applied Data & AI Programme | RCFI Academy" },
  { path: "/academy/digital-health-interoperability/", title: "Digital Health Interoperability & Governance | RCFI Academy" },
  { path: "/academy/digital-trust-cyber/", title: "Digital Trust & Cyber Defence | RCFI Academy" },
  { path: "/academy/executive-briefings/", title: "Executive Briefings | RCFI Academy" },
  { path: "/academy/modern-engineering/", title: "Modern Engineering Programme | RCFI Academy" },
  { path: "/verify/", title: "Verify a Document | RCFI" },
  { path: "/trust/", title: "Trust Center & CA Repository | RCFI Technology" },
  { path: "/privacy/", title: "Privacy Policy | RCFI Technology" },
  { path: "/terms/", title: "Terms of Service | RCFI Technology" },
  { path: "/partners/", title: "Partners & Ecosystem | RCFI Technology" },
  { path: "/ecosystem/", title: "Ecosystem & Strategic Partners | RCFI Technology" },
  { path: "/partners/konza/", title: "Konza Technopolis Partnership | RCFI Technology" },
  { path: "/partners/dha/", title: "Digital Health Agency Partnership | RCFI Technology" },
  { path: "/partners/crown-interactive/", title: "Crown Interactive Partnership | RCFI Technology" },
  { path: "/partners/intellisoft/", title: "Intellisoft Consulting Partnership | RCFI Technology" },
  { path: "/insights/", title: "Insights — The Trust Layer | RCFI Technology" },
  { path: "/impact/", title: "Impact Stories | RCFI Technology" },
  { path: "/variants/home-2/", title: "Home (variant 2) | RCFI Technology" },
  { path: "/variants/home-3/", title: "Home (variant 3) | RCFI Technology" },
  { path: "/variants/home-4-dark/", title: "Home (variant 4, dark) | RCFI Technology" },
  { path: "/variants/certysign-2/", title: "CertySign (variant 2) | RCFI" },
  { path: "/variants/certysign-3-dark/", title: "CertySign (variant 3, dark) | RCFI" },
  { path: "/variants/elano-2/", title: "Elano (variant 2) | RCFI" },
  { path: "/variants/prezio-2/", title: "Prezio (variant 2) | RCFI" },
];
