// Tailwind config exactly as Stitch exported it for this page.
// Only `content` (which files to scan) and the CDN plugins it loaded are added.
const stitch = {darkMode:"class",theme:{extend:{colors:{"on-primary-container":"#7fb99c","inverse-primary":"#98d3b5","on-secondary-fixed-variant":"#005236","tertiary-fixed-dim":"#b5ccc2","outline-variant":"#c0c9c2","primary":"#003221","tertiary-fixed":"#d1e8dd","inverse-on-surface":"#eaf1ff","on-primary-fixed":"#002114","surface-container-lowest":"#ffffff","surface-container-high":"#dce9ff","primary-fixed-dim":"#98d3b5","background":"#f8f9ff","on-secondary-fixed":"#002113","surface-container-highest":"#d5e3fc","surface-variant":"#d5e3fc","secondary-container":"#6cf8bb","surface-tint":"#306951","on-primary-fixed-variant":"#14503a","on-tertiary-fixed-variant":"#374b43","on-tertiary":"#ffffff","surface-bright":"#f8f9ff","on-secondary":"#ffffff","surface":"#f8f9ff","primary-fixed":"#b4f0d1","inverse-surface":"#233144","surface-container":"#e6eeff","secondary-fixed":"#6ffbbe","on-tertiary-container":"#9cb2a8","primary-container":"#0b4a34","on-surface-variant":"#404943","surface-dim":"#ccdbf3","outline":"#707973","on-primary":"#ffffff","on-background":"#0d1c2e","on-error-container":"#93000a","tertiary-container":"#31453e","on-tertiary-fixed":"#0b1f19","error":"#ba1a1a","surface-container-low":"#eff4ff","secondary-fixed-dim":"#4edea3","on-secondary-container":"#00714d","tertiary":"#1b2f28","secondary":"#006c49","on-surface":"#0d1c2e","on-error":"#ffffff","error-container":"#ffdad6"},borderRadius:{DEFAULT:"0.25rem",lg:"0.5rem",xl:"0.75rem",full:"9999px"},spacing:{"space-xl":"2.5rem","margin-mobile":"1rem","space-sm":"0.5rem",gutter:"1.5rem","space-md":"1rem","space-xs":"0.25rem",margin:"2rem","space-lg":"1.5rem","gutter-mobile":"1rem"},fontFamily:{"display-lg":["Plus Jakarta Sans"],"display-lg-mobile":["Plus Jakarta Sans"],"headline-lg-mobile":["Plus Jakarta Sans"],"headline-md":["Plus Jakarta Sans"],"body-lg":["Plus Jakarta Sans"],"label-md":["Plus Jakarta Sans"],"headline-lg":["Plus Jakarta Sans"],"title-md":["Plus Jakarta Sans"],"label-sm":["Plus Jakarta Sans"],"headline-sm":["Plus Jakarta Sans"],"body-md":["Plus Jakarta Sans"]},fontSize:{"display-lg":["48px",{lineHeight:"56px",letterSpacing:"-0.02em",fontWeight:"700"}],"display-lg-mobile":["32px",{lineHeight:"40px",letterSpacing:"-0.01em",fontWeight:"700"}],"headline-lg-mobile":["26px",{lineHeight:"34px",letterSpacing:"-0.01em",fontWeight:"700"}],"headline-md":["28px",{lineHeight:"36px",letterSpacing:"-0.01em",fontWeight:"600"}],"body-lg":["16px",{lineHeight:"26px",fontWeight:"400"}],"label-md":["13px",{lineHeight:"18px",letterSpacing:"0.01em",fontWeight:"500"}],"headline-lg":["36px",{lineHeight:"44px",letterSpacing:"-0.02em",fontWeight:"700"}],"title-md":["18px",{lineHeight:"26px",fontWeight:"600"}],"label-sm":["11px",{lineHeight:"16px",letterSpacing:"0.03em",fontWeight:"600"}],"headline-sm":["20px",{lineHeight:"28px",fontWeight:"600"}],"body-md":["14px",{lineHeight:"22px",fontWeight:"400"}]}}}};

module.exports = {
  ...stitch,
  content: { relative: true, files: ["../../../app/services/digital-cloud-engineering/page.tsx"] },
  plugins: [],
};
